### ISSUE TITLE
Need little clarification between Conditions and adding dependency

### ISSUE THREAD

**Issue by hassanrazakhalid** [ProcedureKit/ProcedureKit#389]
Hello
i need a little clarification between Conditions and adding dependency. As far i have understood Conditions are evaluated first and then that specific operation and when adding dependency again dependent operations are executed first and then that specific operation. Consider a scenario say A,B,C are either some preconditions that need to be fullfilled and G is the operation. Now i can fullfil the conditions either  by using addcondition or addDependency. The result is same which is if all the conditions are met or all the dependency operations are done. Then operation G will be executed.
The question is : What is the difference between the two and under what scenario should i use conditions or dependencies. thanks in advance

**Comment by danthorpe** [comment]
Hi @hassanrazakhalid, firstly, consider an `Operation` which is the "target operation". You can add dependencies and conditions to it. But what does this mean?

Conceptually, a _condition_ is just something which must be satisfied for the target operation to be run. Conversely, a dependency is another operation which will be executed before the target operation can become ready. Adding a dependency is a general mechanism to ensure ordering of operation. Additionally a condition may have its own dependency which which may be required to execute before the condition can be _evaluated_.

In _Operations v3_, `OperationCondition` was replaced with `Condition`, which is actually an `Operation`. Additionally, the way that `Operation` evaluates all of its conditions is by scheduling them as dependencies.

So, what's the difference?

The difference is that: **a dependency cannot prevent the target operation from being executed**.

So, if you want to determine whether to perform an operation at run time (i.e. based on unknown information at compile time), you need some _logic_, which is best expressed separately from _functionality_. This can be done in a condition, i.e. the condition attaches the logic to the functionality, and it can then either be satisfied: the functionality occurs, or not satisfied: functionality does not occur.

Your example above also conflates the concept of a "condition is met" with "an operation finished". This is a recurring misunderstanding with `NSOperation` and dependencies. `NSOperation` has no concept of failure. Instances have a very simple state machine, and when a dependency finishes the next one becomes ready. There is no concept of evaluating whether or not the instanced "failed" this is entirely a definition for the application. So, given that dependencies cannot prevent the target operation from executing - you cannot use dependencies alone for when the conditions are not met?

This is why the framework has `Condition` because it allows you to evaluate a condition as either `.Satisfied` or `.Failed`, which in turn is evaluated after its dependencies, but before the target operation becomes ready - and this is used to cancel the target operation in the event the condition is not met.

**Comment by hactar** [comment]
@danthorpe: thanks for the detailed explanation of this - this should go into the updated documentation imho. Also, how does this now work with the new .ready(.success) and .ready(.failure) concept?
