### ISSUE TITLE
Observers not supported in Objective-C

### ISSUE THREAD

**Issue by ryanjm** [ProcedureKit/ProcedureKit#402]
I'm starting to like using `DidFinishObserver` to handle the callback for when a `GroupOperation` is completed. It gives me more insight into the errors incase I need to not do the next action based on that.

It works great in Swift, but since it is a `struct` it isn't supported in my Objective-C code.

This also applies to the other observers as well. 

As a side note: `AlertOperation` also can't be used in Objective-C.

**Comment by danthorpe** [comment]
Hi @ryanjm, sorry for the delay getting back to you about this.

At the moment, we don't intend to make the block based `struct`s available to Objective-C. However, what we can do, (see #441) is make it so that the protocols are available in Objective-C, which would allow framework consumers to create their own Objective-C types to act as observers.

**Comment by ryanjm** [comment]
Thanks @danthorpe.

**Comment by danthorpe** [comment]
@ryanjm - actually, spoke a bit too soon, see my comments in #441.
