### ISSUE TITLE
[Question] Location Operation in 4.0.0 Beta 2

### ISSUE THREAD

**Issue by fcobia** [ProcedureKit/ProcedureKit#495]
We have been using the Operations framework for a while and had created our own branch for Swift 3.0. I would like to get back to ProcedureKit and most things have gone smoothly. However, we used:

 ```swift
operation.attach(condition: AuthorizedFor(Capability.Location(.whenInUse)))
```

There does not seem to be location in Capability. Am I missing something or is that just missing from the 4.0.0 code right now?

**Comment by danthorpe** [comment]
Hi @fcobia - great to hear you're trying the _ProcecureKit_ v4 betas 😁, and that it's gone smoothly so far.

At the moment, the _Capability.Location_ capability is not done, which is why your line above is not compiling. This should drop in beta 3. Although the support for capabilities, including the `AuthorizedFor` condition is in beta 2, so if you want to put together your own location capability it would see you over the hurdle in the short term. Beta 3 is unlikely to get done until next weekend, as part of a `ProcedureKitLocation` framework.

**Comment by danthorpe** [comment]
Hi @fcobia - these are now available in Beta 3. Gonna close this for now - please comment if you have any issues 😀
