### ISSUE TITLE
Naming Discussion

### ISSUE THREAD

**Issue by martnst** [ProcedureKit/ProcedureKit#512]
Hi @danthorpe , 

I would like to have more of a chat about naming things. I believe it's very important to have good names. Here are some issues I ran into while trying to further understand everything. I am still on the `development` branch mostly. 

1. I don't thinks it good to name all the protocols `…Protocol`.  I think `...Type` as you had before is a better choice if required. Otherwise I thinks sth. like `protocol Foo`, `class DefaultFoo: Foo` is better. 

I currently tried to adopt the CloudKit condition. Therefore I looked at the [Capability](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/Capability.swift) in the dev branch. 

- `public struct VoidStatus: AuthorizationStatusProtocol, Equatable`: Looking at it for instance it's a perfect example that the `Protocol` prefix on `AuthorizationStatusProtocol` is unnecessary. 

Here is my take on renaming things in this file: 

From my understanding `AuthorizationStatusProtocol` aims to abstract system Status enums such as `EKAuthorizationStatus` or `CKAccountStatus`.  I would name it just plain **`AuthorizationStatus`**

- `CapabilityProtocol`: Since there os no real implementation name this protocol **`Capability`**. 

- `public class GetAuthorizationStatus<Status: AuthorizationStatusProtocol>: Procedure, ResultInjectionProtocol`: From the definition of the class I can get that `GetAuthorizationStatus` actually is a `Procedure`, however from the man I can not get that. Also the method that actually performs it's job is called `determineStatus`. Hence rename it to either **`GetAuthorizationStatusProcedure`** or **`DetermineAuthorizationStatusProcedure`**. 

- `public class Authorize<Status: AuthorizationStatusProtocol>: GetAuthorizationStatus<Status>`: similar to `GetAuthorizationStatus`. Should be named `AuthorizeProcedure` or **`AuthorizeCapabilityProcedure`**  to be more precise. 

- `public class AuthorizedFor<Status: AuthorizationStatusProtocol>: Condition`: reading this class I now understand where you are coming from with the names. However, I still think this reads badly or even misleading. For example at `add(dependency: Authorize(base))` might be read as a function to authorize something being called. What it actually does though is add an `Operation` / `Procedure` which will perform the Authorization later and therefore is a different behaviour. 

- `// MARK: - AnyCapability`: I skipped this part for now. 

I hope you understand my concerns and am looking forward to you feedback on this.

**Comment by martnst** [comment]
I spend some more time understanding the Capability design. It's a great generic implementation, however kinda hard to get in.

**Comment by danthorpe** [comment]
Hi @martnst - some interesting points.

I also much prefer `...Type` protocol names. However, the Swift team have either got rid of these entirely in Swift 3.0, see: `SequenceType` -> `Sequence`. Or they have changed `...Type` to `...Protocol`, see: `GeneratorType` -> `IteratorProtocol`.

Having said that, there are only a handful of `...Protocol` named protocols in the Swift 3.0 standard library. So, I think we can definitely improve things to minimise its usage in _ProcedureKit_.

- `AuthorizationStatusProtocol` - can certainly be renamed to `AuthorizationStatus` seeing as the associated type in `CapabilityProtocol` is just `Status`. Pull request for this would be welcome!

- `CapabilityProtocol` - in _Operations_ all of the capabilities provided by the framework were nested under a `Capability` type. e.g. `Capability.Location()`. I have done the same in _ProcedureKit_ so far, but I'm not strongly adhered to it. Will have a think and see what other people say.

- `GetAuthorizationStatus`, `Authorize` etc - fair point.

- `AuthorizedFor` - not really sure what your issue with this is. It's adding a dependency. It doesn't perform the authorisation later - it performs it before, because its a dependency.


Anyway, thanks for the feedback - will consider it all as the betas progress. In general, I think you make some fair points. At the moment, I'm a little bit too close to the code, as I've _just_ written it. There are tasks to document all of these public APIs which, when complete, will hopefully explain how the procedures should be used more clearly. I use this sort of as a spell checking exercise too, ensuring consistency and correctness.

**Comment by martnst** [comment]
Thx for renaming the protocol. Unfortunately I was busy with other projects and even just read your response. Maybe I can catch the next opportunity to contribute some changes via pull requests.…
