### ISSUE TITLE
Why not make AlertProcedure open?

### ISSUE THREAD

**Issue by automactic** [ProcedureKit/ProcedureKit#674]
I tried to subclass AlertProcedure, but failed. 

Could you please consider make AlertProcedure open? So I don't have to configure it twice if I want to present the same alert from 2 different places.

**Comment by danthorpe** [comment]
Hi @automactic - yes, will certainly look at it. There are some alternatives options though instead of subclassing. I think static functions in extensions is a nice way of avoiding subclassing but providing convenience at the importing module's scope.

```swift
extension AlertProcedure {

    static func makeStandardAlert(presentAlertFrom presenting: PresentingViewController) -> AlertProcedure {
        let alert = AlertProcedure(presentAlertFrom: presenting)
        // configure etc
        return alert
    }
}
``` 

and then, in your view controller, you'd do..

```swift
let alert = AlertProcedure.makeStandardAlert(presentAlertFrom: self)
queue.add(procedure: alert)
```

Obviously, function parameters with default values here are very powerful Swift features. 😊

**Comment by automactic** [comment]
Now that I think of it, making it public make a lot sense. You definitely don't want people to add their own actions and forgot to call `finish()`. But on the other hand `var alert: UIAlertController` in `AlertProcedure ` is already public.
