### ISSUE TITLE
How to best handle API error responses

### ISSUE THREAD

**Issue by lukeredpath** [ProcedureKit/ProcedureKit#683]
I'm trying to design an API client using Operations (as we're not currently on Swift 3 all of my examples are using Operations 3.4.1).

The high level design goal is to encapsulate different requests to parts of an HTTP API as an operation. So, if my API has an endpoint `GET /users` I want an operation called `GetUsers`. This operation is a `GroupOperation` that composes the individual steps.

I have the following operations:

- `PerformNetworkRequest` which takes an abstracted `NetworkRequest` struct as a requirement. This is mostly just a thin wrapper around Alamofire.
- `ParseJSONResponse` which takes the `NSData` and `NSHTTPURLResponse` from `PerformNetworkRequest` and parses the data into a `JSON` object using SwiftyJSON.
- `ConverJSONToObject<ResultType: JSONConvertible>`, a generic operation that converts the parsed JSON into a domain object.

These can be composed within a group operation to execute an API request, for example:

```swift
let fetcher = PerformNetworkRequest(request)
        
let parser = ParseJSONResponse()
parser.injectResultFromDependency(fetcher)
        
let converter = ConvertJsonToObject<ResultType>()
converter.injectResultFromDependency(parser)
```

The `result` of the conversion operation is exposed as the `result` of the overall group operation.

Now here's my issue: there's obviously various things that can go wrong at each step. What I particularly want to handle is API errors. For the networking operation, there are effectively 4 outcomes:

1. The network operation is a success and we get a 2xx response code and a JSON object in the response.
2. The network operation fails entirely (e.g. due to lack of connectivity)
3. The server returns a 5xx error (no data in the body)
4. The server returns a 4xx client error and includes a JSON error object in the response.

I think number 2 and probably number 3 should be handled in `PerformNetworkRequest`. The question is how to handle number 4. I still need to pass the data on to `ParseJSONResponse` to parse the error JSON, but then it really needs to be converted into a different object (some kind of `APIError` struct). I could conceivably doing this by using my `ConvertJsonToObject<APIError>` operation but where do I put this logic if I'm already adding a converter operation to the group?

How would you handle each of these cases?

Ultimately, at the highest level, users of the operation should be able to see if it succeeded (and get hold of the resulting object) or failed (and if there was a client error, get the JSON error object).

**Comment by lukeredpath** [comment]
Now I've described my problem I'll elaborate on some of the ideas I've had.

1. Don't schedule the `ConvertJsonToObject` operation until the `ParseJSONResponse` operation has finished. At this point I can expect the JSON keys and add the appropriate operation to the queue. The `PerformNetworkRequest` should treat connection errors and 500 responses as an error and pass those on to `finish()` but not 400 errors. 

2. Have the `ConvertJsonToObject` operation check if the JSON contains error keys and return an `APIError` object instead of the domain object. The group operation should expose some kind of wrapper result type rather than the domain object, e.g.:

```
enum APIResult<DomainObject> {
  case success(DomainObject)
  case error(APIError)
  case failure
}
```

Neither of these seem quite right. I've also experimented with having some kind of intermediate operation that interprets the result of the network operation and schedules the appropriate operations but this started to get complicated and messy.

**Comment by lukeredpath** [comment]
So I've got a working solution so far. Its not perfect but its not too complicated.

All of my API operations inherit from a base `APIRequestOperation<T>`. The high level goal was for this operation to have a `result` of type `T ` if it was successful, otherwise it has errors. If there was a client error (which we parse from the JSON response into an `APIClientError`) this is exposed as an associated value of an error case, e.g.:

```swift
enum APIRequestError {
  case clientError(APIClientError)
}
```

To make this work I had to do a number of things:

1. Change `PerformNetworkRequest` so that it's result type is not `(data, response)` but a new `NetworkResponse` type. Its job is to take a `NetworkRequest` and return a `NetworkResponse` which can be a success response, client error or server error. This operation only fails if it encounters an invalid response or a connection failure.

2. Change `ParseJSONResponse` to take a `NetworkResponse`. If this is nil or its a server error response, the operation is cancelled with an error, otherwise it parses the JSON.

3. Defer adding the `ConvertJSONToObject` operation. This is handled in `APIRequestOperation<T>` in `willFinishOperation()`. When the `ParseJSONResponse` operation is finished, it checks to see what kind of `NetworkResponse` it parsed and adds the appropriate converter operation to the group.

4. Finally, when the converter operation finishes, if it was a success response it stores the result, otherwise it finishes with `APIRequestError.clientError`.

Could I have done this a better way?

**Comment by jshier** [comment]
For things like this I usually don't see the usefulness of having separate procedures for networking, JSON parsing, and value decoding. Since you're already wrapping Alamofire, putting all of that logic inside the Alamofire call is much simpler. Using a custom `ResponseSerializer` type can get you all of your generic value decoding in the Alamofire response handler. That way all errors come out of the single procedure. 

Here's my `NetworkProcedure` that generic for both the request and the response value:
```swift
final class NetworkProcedure<T, U>: Procedure where T: URLRequestRoutable, U: Decodable, U == U.DecodedType {
    
    typealias NetworkCompletionHandler = (_ result: Result<U>?) -> Void
    
    private (set) var response: DataResponse<U>?
    
    private let parameters: T
    private var request: Request?
    private let completionQueue: DispatchQueue?
    private let completionHandler: NetworkCompletionHandler?
    
    var result: Result<U>? {
        return response?.result
    }
    
    init(parameters: T, completionQueue: DispatchQueue? = nil, completionHandler: NetworkCompletionHandler? = nil) {
        self.parameters = parameters
        self.completionQueue = completionQueue
        self.completionHandler = completionHandler
        
        super.init()
        
        name = "NetworkProcedure<\(T.self), \(U.self)>"
    }
    
    override func execute() {
        guard !isCancelled else { return }
        
        request = Communicator.request(parameters).responseValue(queue: executingQueue?.underlyingQueue) { (response: DataResponse<U>) in
            self.response = response
            let error = (self.isCancelled) ? self.result?.error?.filterCancellation() :
                                             self.result?.error
            
            defer { self.finish(withError: error) }
            
            guard !self.isCancelled else { return }
            
            if let completionHandler = self.completionHandler {
                (self.completionQueue ?? .main).async { completionHandler(self.result) }
            }
        }
    }
    
    override func procedureDidCancel(withErrors: [Error]) {
        request?.cancel()
        
        // Do not call finish() here as the Alamofire response handlers are called in either case.
    }
    
}

extension Procedure {
    
    var executingQueue: OperationQueue? { return .current }
    
}

extension Error {
    
    func filterCancellation() -> Error? {
        if let urlError = self as? URLError, urlError.code == .cancelled {
            return nil
        } else {
            return self
        }
    }
    
}
```
Now I have a procedure from which I can get the result of request serialization, networking, parsing, and decoding. Chaining this, or adding observers, makes it easy to use, rather than having a big chain of procedures you have to use.

**Comment by lukeredpath** [comment]
Hmm, personally I find pushing all these different responsibilities into a single operation defeats the object of having small composable operations. Doing all in one is easier but I'm not sure I'd agree that it is simpler. Having them separate makes them very simple to unit test and also understand what each operation does, then you just need a few integration tests around the group operation.

There's minimal impact on users of the library as all of this is internal - API requests are represented by high level operations (that sub-class my base API request operation), they never need to initialise and chain these operations together.

I'd also prefer not to rely too much on Alamofire features, I'm hopeful we can move away from it at some point and just use the networking stuff in ProcedureKit once we can upgrade to Swift 3.

**Comment by jshier** [comment]
In that case I'll just say that using subclasses for every network operation scales terribly. I did the same thing last year and it just didn't work out well. I eventually figured out how to make my network operations properly generic and was able to delete all of my subclasses down to one class. If you really want to have a `GetUser` operation, just make it `typealias GetUser = NetworkOperation<User>`. Otherwise I've recently started using a more protocol based approach to expose only functions publicly, so the underlying operation type isn't really used much. So rather than consumers needing to allocate an operation and enqueue it, they just run `fetchWhatever()` and the protocol takes care of the rest.

**Comment by lukeredpath** [comment]
> So rather than consumers needing to allocate an operation and enqueue it, they just run fetchWhatever() and the protocol takes care of the rest.

That's exactly what I am trying to avoid. I don't think it's a burden to create an operation and add it to a queue. 

I'm not sure what issues you had with scaling this design. I can see how a typealias would work for operations that just fetch something but operations that have inputs need their own initialisers.

**Comment by jshier** [comment]
I don't get it, you're trying to avoid a simple API footprint? The purpose of my protocol-based approach was to both minimize the amount of work consumers had to do to get the API working and reduce the complexity of the implementing code, especially in view controllers.

Rather than every consumer having to allocate and enqueue anything, I created an architecture by which merely adopting a protocol makes the functionality available. That way, not only is the API as simple as possible, but it can be consumed from multiple points without having to repeat code. It also encapsulates that individual bit of API usage in a single call, making it trivial to test. It's the difference between having to do this every time you want to get the user:
```swift
class SomeViewController: UIViewController {

    func fetchUser() {
        let operation: NetworkOperation<User> = NetworkOperation(resource: .user) { user in
            // Do something with user
        }
        networkOperationQueue.addOperation(operation)
    }

    func needToGetUserInHere() {
        fetchUser()
    }

}
```
And this:
```swift
protocol UserFetching { }

extension UserFetching {

    func fetchUser(completionHandler: UserCompletionHandler) {
        let operation: NetworkOperation<User> = NetworkOperation(resource: .user, completionHandler: completionHandler)
        networkOperationQueue.addOperation(operation)
    }

}

class SomeViewController: UIViewController {

    func needToGetUserInHere() {
        fetchUser { user in
            // Do something with user
        }
    }

}

extension SomeViewController: UserFetching { }
```
Hopefully you can see how separating out the operation machinery from the use site will scale far better in the protocol scenario than the direct usage one. Plus, this is really just the most basic protocol usage. My actual implementations can store the value to an ivar using an observer, manage HUD views, persist things to `UserDefaults`, etc., all done generically so it can be used for any type of network procedure.

This is also what I meant by saying that subclasses won't scale well. Unless you only have a few different types to download, you'll so wind up with dozens of subclasses, as I did, all of which are essentially the same. Hopefully these are write once, use many classes, but it's still a lot of overhead if you ever need to change anything, and the Swift compiler still has performance issues that are exacerbated by the number of files it has to compile.

And by the way, typealiases work fine with initializers. It's also why my network procedures are generic for both the request parameters and the response, so I can use it generically even for procedures that take many different parameters. It's all just a single value.

**Comment by jshier** [comment]
I lost a whole big reply, but suffice it to say that I don't think consumers of your API should be exposed to the implementation detail that is allocation and enqueuing an operation. My solution was to put such implementation details behind protocols and their extensions which consumers could then to conform to. This also allowed automatic management of things like HUDs, persistence of various types, and alert presentation through the use of observers.

As for using typealiases, they work just fine with initializers, you just need to make those generic as well. I was able to do so by wrapping the parameters of a request into their own type (which can generate it's parameters dictionary for Alamofire), as you can see in the definition of my `NetworkProcedure`. That way it can take any request to my API and return any value, as defined by the generics.

**Comment by danthorpe** [comment]
Hi @lukeredpath @jshier - just catching up on some issues, and reading through this. Some interesting discussion points! As always, there is more than one way to get stuff done.

Personally, I would almost certainly have a base class (`GroupProcedure`) which creates a network request, enqueues it, (using [`NetworkProcedure`](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitNetwork/Network.swift#L159)) and then decodes the response into a domain object. So this would require it to be generic over the response object, and require an initialiser for the request.

Whether this then needs to be subclassed for further specialisation is a decision that can be deferred. I do like the technique of using typealiases.

**Comment by danthorpe** [comment]
Doing some housekeeping, closing this issue.
