### ISSUE TITLE
Problem using Input-, OutputProcedure in Protocol for DependencyInjection

### ISSUE THREAD

**Issue by vander2675** [ProcedureKit/ProcedureKit#695]
Hey,
I'm trying right now to build my complete business Logic using ProcedureKit. I think for this a great Tool would be to use Dependency Injection with Composition Root, to build up my Dependency Graph.

I'm having trouble setting it up with my Input and Output Procedures, because of the associatedTypes in these Protocols. I would like to set them using a Protocol and not to subclass it, to register it in my Composition Root. 

I would love something like this (I know it doesn't compile 🙃 ):
``` swift
import UIKit

protocol handleJSONUserResponse: ProcedureProtocol, InputProcedure, OutputProcedure {
    
}

extension handleJSONUserResponse {
    typealias Input = JSON
    typealias Output = User
}
```

I just can't get my head around this without subclassing Procedure. Is there any possible way I don't know yet. I know it's not a major issue if I use Subclassing for Abstraction.

Thank you very much in Advance for all Tips!

**Comment by danthorpe** [comment]
Well, essentially, you want to create a structure for performing arbitrary mappings. This is pretty common, but because each mapping, e.g. `JSON` -> `User` is unique you will need to provide either, functions or classes for each distinct mapping.

With _ProcedureKit_ the easiest way to do this is to use the `TransformProcedure` class. It would be something like this...

```swift
typealias HandleJSONUserResponse = TransformProcedure<JSON, User>

let handleJSONUserResponse = HandleJSONUserResponse { json in
    // Perform your mapping here from JSON to User
    return User(fromJSON: json)
}
```

Why does this work? Well, `TransformProcedure` is a subclass which conforms to all of those protocols, and defines associated types, `Input` and `Output` and then it allows a block to perform the transform (when the operation is executed).

Having a protocol, which no subclass which conforms to the protocol (or retroactive modelling) will not help you achieve what you want.

**Comment by vander2675** [comment]
Oh great that looks really handy. But I'cant really register this in my Composition Root, to hide the real Implementation behind some Abstraction.

**Comment by danthorpe** [comment]
You could register functions instead? Sorry, I'm not that familiar with a Composition Root.

**Comment by vander2675** [comment]
I think I'll use subclasses for the most Part. But thank you very much!
