### ISSUE TITLE
Usage of Group Procedure ? 

### ISSUE THREAD

**Issue by mateo666** [ProcedureKit/ProcedureKit#709]
First of all 
Any documentations available for the latest release ?
Seems the documentation i see is no longer relevant ?

I'm trying to get group operations to work properly but can't figure what is the right way to use them...

here is a simple group operation i have
```swift
class GetAndProcessDcryptorStatusProcedure : GroupProcedure, InputProcedure{
    
    public var input: ProcedureKit.Pending<String> = .pending
    public var output:DcryptorData?
    
    init(_ serialCrc:String){
        if !serialCrc.isEmpty{
            input = .ready(serialCrc)
        }
        
        
        let opDownload = GetDcryptorStatusProcedure(serialCrc)
        let opProcess = ProcessDcryptorProcedure()
        opProcess.addDependency(opDownload)
//        opProcess.add(condition: NoFailedDependenciesCondition())
        opProcess.injectResult(from: opDownload)
        
        super.init(operations: [opDownload, opProcess])
        name = "GetAndProcessDcryptorStatusProcedure"
        
        opDownload.addDidFinishBlockObserver { (procedure, errors) in
            guard errors.isEmpty else{return}
        }
        opProcess.addDidFinishBlockObserver { (procedure, errors) in
            guard errors.isEmpty else{return}
            self.output = procedure.output
        }
    }
    
//    override func child(_ child: Operation, willAttemptRecoveryFromErrors errors: [Error]) -> Bool {
//        return false
//    }
}
```

So each procedure of this group can finish with an error. I want to finish the group procedure when one child procedure finishes with an error. 
And i want to get that error only when the group finishes.

I tried with NoFailedDependenciesCondition but it seems that other child procedures still get executed. and the returned errors contain a lot of fail dependency errors 

Can someone point out what is the correct way of handling this ?
And a link to the current documentation would be awesome !

thanks
mat

**Comment by swiftlyfalling** [comment]
@mateo666: You're on the right track. Overriding `child(_: willAttemptRecoveryFromErrors:)` is precisely what you should do to manage the aggregated errors in the GroupProcedure.

(Perhaps that method ought to be renamed to something like `child(_: willHandleErrors:)` in the future.)

Here's one option that could go into your `GroupProcedure` subclass:

```swift
override func child(_ child: Operation, willAttemptRecoveryFromErrors errors: [Error]) -> Bool {
    // Check child's dependencies.
    // If any dependency has errors, ignore the errors from this child.
    // (i.e. Do not aggregate the child's errors into the final errors of the GroupProcedure)

    func operationHasDependenciesWithErrors(_ op: Operation) -> Bool {
        for case let dependency as Procedure in op.dependencies {
            guard dependency.errors.isEmpty else { return true }
        }
        return false
    }

    guard !operationHasDependenciesWithErrors(child) else {
        // Filter out errors from children that have failing dependencies
        //
        // Returning `true` ensures that the errors from this child Procedure
        // are not aggregated into the final errors of the GroupProcedure.
        log.verbose(message: "Ignoring the errors from child with failing dependencies: \(child.operationName)")
        return true
    }
    return super.child(child, willAttemptRecoveryFromErrors: errors)
}
```

With the above, any children **that have dependencies with errors** will not have *their* errors aggregated into the GroupProcedure's final errors.

Now, this doesn't control whether those children with failing dependencies execute, so you'll still need to use either:

1.  `add(condition:NoFailedDependenciesCondition())`
2. `injectResult(from:)`

Both of which will cancel the target operation if there are errors in the dependencies / source of the injected result.

(You shouldn't need to use both, although it also won't hurt anything to do so.)

**Comment by StephenDaedalus** [comment]
I've been struggling with a similar, albeit simpler, scenario. I have a GroupProcedure which kicks off a bunch of `NetworkDownloadProcedure` procedures. Some of these may produce errors because of missing links, etc. I would like to ignore those. If I override `childWillAttemptRecoverFromErrors` and return true, I still see that the error is being propagated into the GroupProcedure so that it doesn't appear to complete without errors. Any insights or suggestions or is a code sample going to be the only way to advise?

**Comment by StephenDaedalus** [comment]
Of course if I call `self.errors.removeAll()` inside the `childWillAttemptRecoveryFromErrors` method it seems to work better. Note that I had tried to just cancel the child operation but wasn't sure that was correct either.

One of the reasons for my confusion is because I'm not sure if any `Repeatable` operations handle the `childWillAttemptRecoveryFromErrors`condition the same way. There are some inline notes about attempting to re-run the operation that confuse me. In addition, CloudKit operations definitely respect that when `childWillAttemptRecoveryFromErrors` returns true, everything still proceeds and the error appears to be swallowed.

If would be nice to be able to pick up any and all errors in a child operation and flag them as handled and thus discardable in the larger `GroupProcedure`. I don't see any examples of this anywhere so I'm not sure if there's an easy path to achieving this.

**Comment by swiftlyfalling** [comment]
@StephenDaedalus: If you override `child(_: willAttemptRecoveryFromErrors:)` in your GroupProcedure subclass, the errors should not be automatically aggregated into the GroupProcedure's final `errors`. If you are seeing otherwise, a reduced code example that exhibits the problem would be appreciated, because it sounds like a bug.

**Comment by mateo666** [comment]
@swiftlyfalling i'm using NoFailDependencies with the function you provided and its working the way i want. 
thanks !
Mat

**Comment by danthorpe** [comment]
Hi, gonna close this for now.
