### ISSUE TITLE
[Question]: Login operation to accessing a secure page

### ISSUE THREAD

**Issue by felixmariaa** [ProcedureKit/ProcedureKit#745]
Hi Dan,

I managed to get the login operation working. But I'm not sure if it's the right way to do things. I've attached the source code that I'm using to test the operations.

The source code has:
A. Operations:
1. LoginOperation - Invokes the login view. 
2. SecureOperation - This is dependent on the LoginOperation. On success, the SecureView is shown. I've added a condition "NoFailedDependenciesCondition". Is this condition required?

B. View Controllers:
1. PublicViewController - This is a public view that doesn't require the user to login. There's a button on the right nav bar to access the secure view.
2. LoginViewController - Contains email, password and submit button. Submit button dismisses the view and invokes finish() on the Login Operation.
3. SecureViewController - This view requires the user to login. For this purpose, I've created a SecureOperation that adds the LoginOperation as a dependency. 

Questions:
1. Am I doing the operations right? 
2. Afraid, that I'm missing something because I noticed a memory leak when running the app. I've attached a screenshot of the same.

Let me know your thoughts. 

Thanks,
Felix Marianayagam.J

![memoryleak 2017-06-15 at 5 57 27 pm](https://user-images.githubusercontent.com/18690008/27182074-ae328580-51f7-11e7-943e-7d166d37e914.png)
[pkTest.zip](https://github.com/ProcedureKit/ProcedureKit/files/1077657/pkTest.zip)

**Comment by danthorpe** [comment]
Hi @felixmariaa, took a quick look at your project - overall looks good.

Having said that, I'm not entirely convinced by the architecture where the login operation is created inside your secure operation as a dependency. To me this is a bit of a code smell.

_ProcedureKit_ allows for a better abstraction of this situation, via capabilities. You would create a `LoggedInCapability` class which would essentially check to see if the user is logged in, and if not, would be perform the `LoginOperation` for you. Then you'd attach a condition `AuthorizedFor(loggedIn)` requirement to your `SecureOperation` instance.

You already have the bits an pieces in place (`if AuthStore.instance.isLoggedIn()`) to check for this.

That possibly sounds like lots of effort, but it does have a clear advantage of decoupling the requirements/dependencies of your operations. You can even remove code from your `LoginOperation` so that it doesn't need to check the logged in status - that is also just handled by the capability.

Check out the old docs on [Capabilities](https://operations.readme.io/docs/capabilities), in _ProcedureKit_ this hasn't changed much, see: [CapabilityProtocol](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKit/Capability.swift#L42) and an example of [LocationCapability](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitLocation/LocationCapability.swift#L44).

**Comment by felixmariaa** [comment]
Thank you. I'll look into Capabilities.

**Comment by danthorpe** [comment]
Okay, gonna close this for now.
