### ISSUE TITLE
[Question] Help needed on starting with ProcedureKitCloud

### ISSUE THREAD

**Issue by felixmariaa** [ProcedureKit/ProcedureKit#746]
Hi Dan,

I'm using CoreData in my App. I'd like to provide an option to store data in the user's iCloud private database. 

The app would need to:
a. Sync data between CoreData and iCloud database. 
b. Subscribe to database change notifications. For example: if the user uses the app in two devices, the change in one device should reflect in the other device.

I noticed that ProcedureKitCloud has been coded to help with the above requirements. I've been browsing through the source for ProcedureKitCloud and it's corresponding tests. Wonder, if you have any documentation on ProcedureKitCloud (or) some simple snippets that would help me get started in the right direction.

Thanks much
Felix Marianayagam.J

**Comment by danthorpe** [comment]
Hi @felixmariaa, not sure how much I can help you here, but I can try.

_ProcedureKitCloud_ wraps up the various `CKOperation` classes from CloudKit so that they fit nicely into a project using _ProcedureKit_ - this means they get things like automatic error handling (for some errors) for free, and can easily support custom error handling.

However, like CloudKit itself, crucially, there are things which it doesn't do. These are:
- there is no mechanism in CloudKit (although I've not watched the WWDC17 videos yet) for persistence or syncing. This is reflected by _ProcedureKitCloud_.
- there is no code to help you "setup" your CloudKit subscriptions & record zones etc etc.

Essentially, there is still quite a bit that you, as an application developer will need to tackle to achieve the above. The good news is that all of that stuff can be written as your own custom `CloudKitSetupProcedure` which should be a `GroupProcedure` subclass, and internally you will be using the various classes provided with _ProcedureKitCloud_. i.e. create zones, subscriptions etc etc

As for syncing - that is also something that you will need to figure out as part of your client side storage system. I can recommend that you check out, [YapDatabase](https://github.com/yapstudios/YapDatabase) and it's support for CloudKit, instead of Core Data. But again, this is really an engineering decision you will need to research and decide on.

**Comment by felixmariaa** [comment]
Thank you.

**Comment by danthorpe** [comment]
Gonna close this now
