### ISSUE TITLE
[Question]: Webinar, Meetup, Discussion Forums or Core Review

### ISSUE THREAD

**Issue by StephenDaedalus** [ProcedureKit/ProcedureKit#783]
I've been using the Operations framework since WWDC 2015. I was using a version of that until I discovered OperationKit. I have steadily kept up with changes through to ProcedureKit. 

I have created numerous examples of Procedures that attempt to utilize some of the most advanced functionalities in the framework, i.e. `GroupProcedure`, `ComposedProcedure`, `InputProcedure`, `OutputProcedure`, etc. 

I would like to contribute to the documentation for the framework but would only want to do so after knowing that my code samples are representative of "Best Practices". I've had to struggle through some challenges because of a dearth of samples and documentation. 

So, the question is:  is there a plan to do any kind of question and answer session for active users, and possible contributors? It could be a recorded Webinar or an in person Meetup. It could be one-time or perhaps span some sequence of dates. 

I think you'd find a number of potential participants and doing so may allow a significant bump in documentation coverage.

**Comment by danthorpe** [comment]
Hi @StephenDaedalus, not really sure how to respond to this really. 🤔

Feel free to share your examples and they can be linked to if they are representative. We (contributors here) can also suggest changes or amendments if there are improvements to be made in the name of "best practice". This is certainly an area where it would be great to share more, and given more time, I would like to publish full example apps written using _ProcedureKit_. But again, as is the nature of open source - anyone can do this, including yourself if you wish.

At the moment, there are no plans for a _ProcedureKitConf_ or similar, although it's certainly something which would be considered if a corporate sponsor or similar were to emerge. In terms of meet-ups and other conferences, there have been quite a few talks given about _Operations_ & _ProcedureKit_, and clearly this is something we would love to see more of. Ones we know about are stored in the repo under `Presentations/`. We've even ran an ad-hoc lab at WWDC.

In terms of documentation, my current focus before work on v5 is to complete [procedure.kit.run/development](http://procedure.kit.run/development). However, there have been contributions to the [wiki](https://github.com/ProcedureKit/ProcedureKit/wiki) coming from the community, which are incorporated, and which we heartily welcome.

I guess ultimately, if you want to contribute, please do so. How? 

- Add pages to, or otherwise augment the wiki, please link to public example projects which have an MIT license. 
- Please submit new questions to the [FAQ](https://github.com/ProcedureKit/ProcedureKit/wiki#asking-questions--getting-help). 
- Create a PR if you wish to add source code documentation, fix bugs, or add missing features. 
- Please submit a PR with your presentation files if you have spoken about _ProcedureKit_ at a meet up.
- Join the Slack channel (DM me on Twitter for an invite) for more active discussions with contributors.
