### ISSUE TITLE
Crash with Xcode 8.3/8.3.3 + ProcedureKit 4.3.0 + Address Sanitizer 

### ISSUE THREAD

**Issue by yageek** [ProcedureKit/ProcedureKit#788]
Using the Address Sanitizer on Xcode 8.3/8.3.3,  the ProcedureKit version 4.3.0, a crash occurs inside the `Operation+ProcedureKit.swift` file.

According to the stack trace, this may be a bug inside `Foundation`.

<img width="1738" alt="screen shot 2017-08-14 at 13 18 05" src="https://user-images.githubusercontent.com/170917/29270035-fcfc5b24-80f4-11e7-8756-208a30dbbc84.png">

**Comment by swiftlyfalling** [comment]
I have seen odd issues with Xcode 8.x's Thread Sanitizer and Address Sanitizer that *don't* seem to reproduce on Xcode 9 beta. Some of them may have been core (Swift core or otherwise) issues that were fixed, some of them may have been edge-cases in the Sanitizers themselves.

If this doesn't reproduce in Xcode 9 beta, it may belong in that group.

**Comment by danthorpe** [comment]
Closing this for now.
