### ISSUE TITLE
Installing trough cocoapods is not working

### ISSUE THREAD

**Issue by myexec** [ProcedureKit/ProcedureKit#806]
I'm trying to install ProcedureKit to a new project via cocoapods but there is error:

Analyzing dependencies
Fetching podspec for `ProcedureKit` from `submodules/ProcedureKit`
[!] No podspec found for `ProcedureKit` in `submodules/ProcedureKit`

Here is my podfile:

target 'Code9' do
  platform :ios, '10'
  use_frameworks!
  pod 'ProcedureKit/All', :path => 'submodules/ProcedureKit'
  pod 'ProcedureKit/Mobile', :path => 'submodules/ProcedureKit'  
end

**Comment by danthorpe** [comment]
Hi @myexec 

Did you update/checkout or otherwise prepare the source in `submodules/ProcedureKit` e.g.

> $ cd submodules/ProcedureKit
$ git fetch origin
$ git checkout 4.4.0
HEAD is now at 30d6781... 4.4.0 (#805)
$ cd ../..
$ bundle exec pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `ProcedureKit` from `submodules/ProcedureKit`
Fetching podspec for `TestingProcedureKit` from `submodules/ProcedureKit`
Downloading dependencies
Installing ProcedureKit 4.4.0 (was 4.0.0)
Installing TestingProcedureKit 4.4.0 (was 4.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 2 total pods installed.
$

**Comment by danthorpe** [comment]
Closing as no response.
