### ISSUE TITLE
inject dependency for running operation

### ISSUE THREAD

**Issue by pronebird** [ProcedureKit/ProcedureKit#819]
Hi,

Is it possible to inject the result from already finished or running operation? It seems that `injectResult` and subsequent call to `inject(dependency: )` adds observers on the dependency which is IIRC not safe to do when the op is already running or finished.

The use case I have is basically related to the fact that my API client returns the operations when it issues requests and adds them into internal queue. At this point the end consumer can either `cancel()` the operation or theoretically inject the result of it into its own operation flow. This is super convenient since I can actually compose the complex logic this way.

i.e:

```
let clientOp = client.doSomethingAndReturnEnqueuedOperation() // OutputProcedure
let showMessageOp = ShowMessageOperation() // InputProcedure

// This is apparently illegal since clientOp is already on some other queue and maybe even running
showMessageOp.injectResult(clientOp)

myInternalQueue.add(operation: showMessageOp)
```

A workaround that comes to my mind is to simply add a `ResultProcedure` with dependency to my "clientOp" which may have finished by then, but it's fine. Then simply hijack the `output` and return it to the end consumer. In that case newly created procedure with dependency is not running yet so it's legal to use it for injection.

**Comment by danthorpe** [comment]
Yeah, you're correct. Because your `client` is add the operations to the queue, there isn't a way for you to add an observer (after it returns) and guarantee that it'll be triggered by the operation, which could have finished before your code runs adding it.

In theory, if your return `Procedure` subclass conforms to `OutputProcedure`, then you could check it's state for `isFinished` and optionally get it's output - but this is not really recommended, as you'll bump into locking/threading issues and it'll result in edge cases and hard to pin down bugs.

You're best bet (I think) is to rethink your architecture. If you know at compile time (because you've written the code that way) that you need to inject the procedure output, then it should be possible to construct this before adding it all to the queue. e.g.

```swift
let showMessageOp = ShowMessageOperation() // InputProcedure
let clientOp = client.doSomethingAndReturnEnqueuedOperation(with: showMessageOp)
```

**Comment by pronebird** [comment]
Good point, thanks for taking time to answer.
