### ISSUE TITLE
ProcedureKitCoreData Has a bug

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [ProcedureKit/ProcedureKit#846]
It should be revised to preform the insert action via a context.preform {} or a context.preformAndWait{} call.

According to the Core data documentation managed object subclasses are not thread safe and therefore should not be passed between threads / queues.

all related operations should not use the actual instance of the mangedObjectCotext that they received via the init call, instead creating a private context to run the procedure in. also you should change all code the calls a fetch action to run in a preform block on the new context

Lastly and most important, mangedObject subclasses are not thread safe, you should not return them via output protocol.

p.s. liked the MakeFetchedResultControllerProcedure looks really useful, although it has the same issue with the "try frc.performFetch()" call

**Comment by danthorpe** [comment]
Thanks @ArkadiYoskovitz - will take a look.

**Comment by danthorpe** [comment]
HI @ArkadiYoskovitz - have addressed this issues in #847 - would be great if you could take a look.

One thing which I still find a bit frustrating with Core Data is that the FRC docs don't explicitly state that you should/must/aught to call `performFetch()` inside a `perform[andWait] {}` block. Given that the FRC holds a strong reference to the MOC, I would have through that this is redundant, as it's taken care of by the FRC. Maybe you're experience has revealed different behaviour though?

**Comment by ArkadiGiniApps** [comment]
Hi,

Due to the lacking documentation I thing that your fix is the right one. You generally call the fetch on frc in your ui code (main queue) so it doesn’t raise an issue but it’s a foot idea to wrap it like you did for the procedure usecase. 

Also liked the new convenience moc creation mechanism. 

But something else popped out, I’m not so sure about the filter procedure. it has all the same issues that I mentioned before about the thread confinement. And I’m not sure how you can fix it or even if you should. Core data provides uniqueness constraint support starting from iOS 9. I think that that’s the usecase you tried to handle here but I might be wrong.

**Comment by danthorpe** [comment]
Oh! @ArkadiGiniApps @ArkadiYoskovitz you are right - didn't see that they added constraints at an entity level. Not used Core Data in a real project for a few years now 🤣 - thanks for the reviewing!

Have remove the Filter procedure - as you're right, not needed if the model is correctly configured, and the merge policy is set correctly.

**Comment by danthorpe** [comment]
Fixed in #847
