### ISSUE TITLE
Custom Procedure with CloudKitProcedure error handling

### ISSUE THREAD

**Issue by imrabti** [ProcedureKit/ProcedureKit#884]
I have a custom RecordZoneProcedure that contain two calls using the CloudkitProcedure one to fetch the record zone and other one to create if no record zone is found.

My question is that if one of the CloudKitProcedure finishes with error, will RecordZoneProcedure also finished with Error (is the error automatically communicated) 

Below I have attached the code RecordZoneProcedure : 

```swift
class RecordZoneOperation: Procedure {
    
    // MARK: - Properties
    
    private let queue = ProcedureQueue()
    private let database = CloudSync.shareInstance.container.privateCloudDatabase
    private let recordZoneId = CloudSync.shareInstance.recordZoneId
    
    override func execute() {
        if self.isCancelled {
            finish()
        }
        
        let createRecordZone = makeCreateRecordZoneOperation()
        let fetchRecordZone = makeFetchRecordZoneOperation(createRecordZone: createRecordZone)
        let finishOperation = BlockProcedure {
            self.finish()
        }
        
        // Add all operations to the queue
        createRecordZone.addDependency(fetchRecordZone)
        finishOperation.addDependency(createRecordZone)
        queue.addOperations([createRecordZone, fetchRecordZone, finishOperation], waitUntilFinished: true)
    }
    
    private func makeCreateRecordZoneOperation() -> Procedure {
        let recordZone = CKRecordZone(zoneID: recordZoneId)
        let operation = CloudKitProcedure { CKModifyRecordZonesOperation(recordZonesToSave: [recordZone], recordZoneIDsToDelete: nil) }
        operation.database = database
        
        return operation
    }
    
    private func makeFetchRecordZoneOperation(createRecordZone: Operation) -> Procedure {
        let operation = CloudKitProcedure { CKFetchRecordZonesOperation(recordZoneIDs: [self.recordZoneId]) }
        operation.database = database
        operation.setFetchRecordZonesCompletionBlock { recordZoneId in
            createRecordZone.cancel()
        }
        
        return operation
    }
}
```

**Comment by danthorpe** [comment]
Hi @imrabti just getting to look at this. 

So, _ProcedureKitCloud_ just gives you a way to insert Apple's CKOperation based classes into a ProcedureKit system. It gives you a bunch of stuff  for free, like auto-retry for many errors.

However, it doesn't (yet) give you an obvious route on how to chain together CK operations, such as _create zone_ -> _fetch records_ -> _modify records_ -> _save records_ etc.

However, _ProcedureKit_ already has a class and types which can be used to encapsulate single unit tasks into higher lever tasks - namely `GroupProcedure`.  I would strongly recommend that you use a `GroupProcedure` and read [these docs](http://procedure.kit.run/development/groups.html).

With `GroupProcedure` you can either, setup all "child" operations as part of its initialiser, or, if that's not possible, (because the child tasks may need to be determined based on the results of a previous one) they can be added using `GroupProcedure`'s API.

In your scenario above, it's best to add a completion handler to the `CKModifyRecordZonesOperation` which should be checked as part of a dependency operation in the group.

---

Another way to approach this problem is to think about the dependencies & errors as _conditions_. For example, your _fetch record zones_ operation requires that the zone has been created. Using the dependency feature of `Operation`/`Procedure` is only half of the solution - as dependent procedures care not about the finished state of their dependencies. However, by encapsulating the state of the CloudKit stack via a Condition e.g. `CreatedRecordZoneCondition` you could define a dependency (of the condition) to create the zone, and attach it to your `FetchRecordZone`. If the condition fails (because there was an error) the `FetchRecordZone` will not not execute

**Comment by imrabti** [comment]
Hi @danthorpe thank you the clarification it is very detailed and precise, now I know I have some refactoring to do :-D
