### ISSUE TITLE
Update to last 5.0.0-beta.2 and get Generic parameter 'T' could not be inferred on all CloudKit Operation

### ISSUE THREAD

**Issue by imrabti** [ProcedureKit/ProcedureKit#889]
After updating to 5.0.0-beta.2 I get now errors on all CloudKit operations : Generic parameter 'T' could not be inferred.
Should I update something ?

**Comment by danthorpe** [comment]
Hi @imrabti - sorry, didn't have time to get to this yet. Will look into it tonight. 

Can you share the error message, and your code which is causing it?

**Comment by danthorpe** [comment]
Hi @imrabti - this is now fixed by the changes in PR #902. Would you be able to compile your project against this branch and let me know?

My own integration project using CloudKit compiles fine (and I did see the original issue you referred to). So, I'm pretty confident, just would like to check that your usage is also okay.

**Comment by danthorpe** [comment]
@imrabti closing this for now - the fix is merged in `development` and will be released in a new Beta in the next day or so.

**Comment by imrabti** [comment]
@danthorpe I just tested on my project it is working smoothly, thanks :-)
