### ISSUE TITLE
Core data insert procedure incorrectly initializes MOC and passes managed objects outside owning queue.

### ISSUE THREAD

**Issue by ericyanush** [ProcedureKit/ProcedureKit#903]
https://github.com/ProcedureKit/ProcedureKit/blob/234d0541f1e453e143359f9cc82d98d1bd383570/Sources/ProcedureKitCoreData/InsertManagedObjects.swift#L56-L58

As per [Apple's documentation](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext), MOCs used in operations need to be initialized on the receiving thread, as the MOC assumes that the owning thread of the context's managed objects is the thread on which the context was initialized.

> You should not, therefore, initialize a context on one thread then pass it to a different thread. Instead, you should pass a reference to a persistent store coordinator and have the receiving thread/queue create a new context derived from that. If you use Operation, you must create the context in main (for a serial queue) or start (for a concurrent queue).

~~Also, having the insert objects procedure `bind(to:)` the async transform procedure allows objects created on one thread to be passed outside of their owning thread and be potentially consumed by another operation running on another thread, or accidentally manipulated using a another context created on another thread. If there is a need to pass objects created inside the procedure to another operation or as output back to the originator of the procedure, they should probably be passes as managed object ids. [Passing objects across threads](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/Concurrency.html#//apple_ref/doc/uid/TP40001075-CH24-SW4)~~

**Comment by danthorpe** [comment]
Hi @ericyanush,

Yeah, I can see that the MOC should actually be initiated at the start of the `AsyncTransformProcedure`, or at least, as part of the group's execute phase, instead of during the group's init method. That would guarantee that it is initialised on the same dispatch queue as the async transform is executed on.

Not entirely sure I follow your comment regarding binding the input of the `InsertManagedObjectsProcedure` to the `AsyncTransformProcedure` instance. Although there are no constraints on the `Item` type, the intention would be that these are PONSOs or structs or basically "dumb" data containers which need to be _mapped_ to managed objects in CoreData. So, there should be no risk to them being created outside of the procedure (in another thread).

The output of `InsertManagedObjectsProcedure` is a `[NSManagedObjectID]`, which, as you know, are safe to the passed between threads.

The `ManagedObject` generic type, is created and accessed (via the block) inside the procedure on its dedicated queue - so this is safe as far as my testing as shown.

**Comment by ericyanush** [comment]
You are correct. I completely missed the fact that it was binding an output of `[NSManagedObjectID]`. Please disregard my comments about passing around managed objects across threads.

**Comment by danthorpe** [comment]
Closing this for now @ericyanush, fixes are in `development` - thanks for raising it! 👍
